import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const db = new DatabaseSync(fileURLToPath(new URL('../data/tiffinflow.db', import.meta.url)));
const hash = password => { const salt=randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password,salt,64).toString('hex')}`; };
const matches = (password, stored) => { const [salt,key]=stored.split(':'); return timingSafeEqual(scryptSync(password,salt,64),Buffer.from(key,'hex')); };

db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), name TEXT NOT NULL, phone TEXT NOT NULL, plan TEXT NOT NULL, monthly_price INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','paused')), created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS deliveries (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), delivered_on TEXT NOT NULL, UNIQUE(customer_id, delivered_on));
CREATE TABLE IF NOT EXISTS pause_windows (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), start_date TEXT NOT NULL, end_date TEXT, reason TEXT);
CREATE INDEX IF NOT EXISTS idx_customers_user_name ON customers(user_id,name);
CREATE INDEX IF NOT EXISTS idx_deliveries_customer_date ON deliveries(customer_id,delivered_on);`);

function seed() { if (db.prepare('SELECT count(*) AS count FROM users').get().count) return; const owner=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run('TiffinFlow Owner','owner@tiffinflow.test',hash('Demo@123')); const customers=[['Aarav Mehta','+91 98765 10482','Standard',3000,'active',17],['Meera Nair','+91 99871 44209','Starter',2400,'paused',14],['Rohan Kapoor','+91 98110 24087','Family',4800,'active',17],['Sana Iqbal','+91 90041 88902','Standard',3000,'paused',12],['Vikram Rao','+91 97683 35167','Starter',2400,'active',16]]; const add=db.prepare('INSERT INTO customers(user_id,name,phone,plan,monthly_price,status) VALUES(?,?,?,?,?,?)'); const delivery=db.prepare('INSERT INTO deliveries(customer_id,delivered_on) VALUES(?,?)'); for(const [name,phone,plan,price,status,days] of customers){const row=add.run(owner.lastInsertRowid,name,phone,plan,price,status);for(let i=1;i<=days;i++)delivery.run(row.lastInsertRowid,`2026-09-${String(i).padStart(2,'0')}`)}} seed();

export function register(name,email,password){ if(!name||!email||!password||password.length<8) throw new Error('Name, email and an 8-character password are required'); const result=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email.toLowerCase(),hash(password)); return createSession(Number(result.lastInsertRowid)); }
export function login(email,password){ const user=db.prepare('SELECT * FROM users WHERE email=?').get(email.toLowerCase()); if(!user||!matches(password,user.password_hash)) throw new Error('Invalid email or password'); return createSession(user.id); }
function createSession(userId){const token=randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,datetime(\'now\',\'+7 days\'))').run(token,userId); return {token,user:db.prepare('SELECT id,name,email FROM users WHERE id=?').get(userId)};}
export function session(token){return db.prepare(`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>datetime('now')`).get(token);}
export function customers(userId,{q='',page=1,limit=5,sort='name',order='asc'}){const safeSort=['name','plan','monthly_price','status'].includes(sort)?sort:'name';const direction=order==='desc'?'DESC':'ASC';const where=`user_id=? AND (name LIKE ? OR phone LIKE ?)`;const args=[userId,`%${q}%`,`%${q}%`];const total=db.prepare(`SELECT count(*) AS total FROM customers WHERE ${where}`).get(...args).total;const rows=db.prepare(`SELECT c.*,count(d.id) AS deliveredDays FROM customers c LEFT JOIN deliveries d ON d.customer_id=c.id WHERE ${where} GROUP BY c.id ORDER BY ${safeSort} ${direction} LIMIT ? OFFSET ?`).all(...args,Number(limit), (Number(page)-1)*Number(limit));return {rows,total,page:Number(page),limit:Number(limit)};}
export function dashboard(userId){return db.prepare(`SELECT sum(CASE WHEN c.status='active' THEN 1 ELSE 0 END) active,sum(CASE WHEN c.status='paused' THEN 1 ELSE 0 END) paused,count(d.id) mealsDelivered,round(sum(c.monthly_price/22.0*COALESCE(x.days,0))) projectedCollection FROM customers c LEFT JOIN deliveries d ON d.customer_id=c.id LEFT JOIN (SELECT customer_id,count(*) days FROM deliveries GROUP BY customer_id) x ON x.customer_id=c.id WHERE c.user_id=?`).get(userId);}
export function addCustomer(userId,input){const {name,phone,plan='Standard',monthlyPrice}=input;if(!name||!phone||!monthlyPrice)throw new Error('name, phone and monthlyPrice are required');return db.prepare('INSERT INTO customers(user_id,name,phone,plan,monthly_price,status) VALUES(?,?,?,?,?,\'active\')').run(userId,name,phone,plan,Number(monthlyPrice)).lastInsertRowid;}
export function setStatus(userId,id,status){const result=db.prepare(`UPDATE customers SET status=? WHERE id=? AND user_id=?`).run(status==='paused'?'paused':'active',id,userId);if(!result.changes)throw new Error('Customer not found');}
export const invoiceAmount = (monthlyPrice, deliveredDays, serviceDays=22) => Math.round(monthlyPrice / serviceDays * deliveredDays);
